"""Demo issues seeded into MongoDB on first startup so the public feed isn't empty."""
from datetime import datetime, timezone

imgPothole = "https://images.pexels.com/photos/6018646/pexels-photo-6018646.jpeg"
imgPothole2 = "https://images.pexels.com/photos/11849379/pexels-photo-11849379.jpeg"
imgGarbage = "https://images.unsplash.com/photo-1762805544399-7cdf748371e0?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzF8MHwxfHNlYXJjaHwyfHxnYXJiYWdlJTIwc3RyZWV0JTIwaW5kaWFufGVufDB8fHx8MTc3NzAxMTY5NXww&ixlib=rb-4.1.0&q=85"
imgWater = "https://images.pexels.com/photos/15206136/pexels-photo-15206136.jpeg"
imgLight = "https://images.pexels.com/photos/9953451/pexels-photo-9953451.jpeg"

DEMO_ISSUES = [
    {
        "issue_id": "PO-DEMO01",
        "title": "Massive pothole causing daily accidents on Hosur Road",
        "description": "A 4-foot wide pothole has formed at the junction near Electronic City flyover. Two two-wheeler accidents reported this week. Urgent resurfacing needed before monsoon.",
        "category": "roads",
        "urgency": "high",
        "status": "in_progress",
        "anonymous": False,
        "photos": [imgPothole, imgPothole2],
        "location": {"address": "Hosur Road, Electronic City Phase 1", "city": "Bengaluru", "district": "Bengaluru Urban", "state": "Karnataka", "pincode": "560100", "lat": 12.8456, "lng": 77.6603},
        "reporter": {"user_id": "demo_arjun", "name": "Arjun Mehta", "anonymous": False, "picture": None},
        "owner_user_id": "demo_arjun",
        "upvotes": 1247,
        "posted_at": datetime(2026, 2, 4, 9, 23, tzinfo=timezone.utc),
    },
    {
        "issue_id": "PO-DEMO02",
        "title": "Garbage uncollected for 8 days in Sector 14",
        "description": "Garbage collection truck has not visited the lane behind community park for over a week. Stray dogs are tearing open bags, creating a health hazard.",
        "category": "garbage",
        "urgency": "high",
        "status": "assigned",
        "anonymous": False,
        "photos": [imgGarbage],
        "location": {"address": "Sector 14, Block C", "city": "Gurugram", "district": "Gurugram", "state": "Haryana", "pincode": "122001", "lat": 28.4701, "lng": 77.0266},
        "reporter": {"user_id": "demo_priya", "name": "Priya Sharma", "anonymous": False, "picture": None},
        "owner_user_id": "demo_priya",
        "upvotes": 634,
        "posted_at": datetime(2026, 2, 6, 17, 40, tzinfo=timezone.utc),
    },
    {
        "issue_id": "PO-DEMO03",
        "title": "Water leakage wasting thousands of litres near Jubilee Hills",
        "description": "A main pipeline has been leaking for 3 days near Road No. 36. Estimated 30,000+ litres of potable water wasted daily. HMWSSB crews acknowledged but no action yet.",
        "category": "water",
        "urgency": "critical",
        "status": "under_review",
        "anonymous": True,
        "photos": [imgWater],
        "location": {"address": "Road No. 36, Jubilee Hills", "city": "Hyderabad", "district": "Hyderabad", "state": "Telangana", "pincode": "500033", "lat": 17.4286, "lng": 78.4066},
        "reporter": {"user_id": "demo_anon1", "name": "Anonymous", "anonymous": True, "picture": None},
        "owner_user_id": "demo_anon1",
        "upvotes": 2104,
        "posted_at": datetime(2026, 2, 5, 6, 15, tzinfo=timezone.utc),
    },
    {
        "issue_id": "PO-DEMO04",
        "title": "Entire lane dark — 11 streetlights non-functional",
        "description": "Every single streetlight on Anna Nagar 2nd Cross has been out for 2 weeks. Residents, especially women and children, feel unsafe after 7 PM.",
        "category": "streetlight",
        "urgency": "medium",
        "status": "resolved",
        "anonymous": False,
        "photos": [imgLight],
        "location": {"address": "Anna Nagar 2nd Cross", "city": "Chennai", "district": "Chennai", "state": "Tamil Nadu", "pincode": "600040", "lat": 13.0878, "lng": 80.2169},
        "reporter": {"user_id": "demo_karthik", "name": "Karthik Subramanian", "anonymous": False, "picture": None},
        "owner_user_id": "demo_karthik",
        "upvotes": 489,
        "posted_at": datetime(2026, 1, 28, 19, 20, tzinfo=timezone.utc),
    },
    {
        "issue_id": "PO-DEMO05",
        "title": "Open drain overflow floods colony during rains",
        "description": "Every time it rains for more than 20 minutes, sewage from the open drain floods into ground floor houses. This has been a recurring issue for 3 monsoons.",
        "category": "drainage",
        "urgency": "critical",
        "status": "submitted",
        "anonymous": False,
        "photos": [imgPothole2],
        "location": {"address": "Lokhandwala Complex", "city": "Mumbai", "district": "Mumbai Suburban", "state": "Maharashtra", "pincode": "400053", "lat": 19.1336, "lng": 72.8346},
        "reporter": {"user_id": "demo_neha", "name": "Neha Iyer", "anonymous": False, "picture": None},
        "owner_user_id": "demo_neha",
        "upvotes": 823,
        "posted_at": datetime(2026, 2, 8, 11, 45, tzinfo=timezone.utc),
    },
    {
        "issue_id": "PO-DEMO06",
        "title": "Signal timing broken — causing 40-minute jams",
        "description": "Traffic signal at main intersection stuck on red-red-red on all approaches during peak hours. Manual traffic police needed but absent.",
        "category": "traffic",
        "urgency": "high",
        "status": "in_progress",
        "anonymous": False,
        "photos": [imgPothole2],
        "location": {"address": "Connaught Place Outer Circle", "city": "New Delhi", "district": "Central Delhi", "state": "Delhi", "pincode": "110001", "lat": 28.6315, "lng": 77.2167},
        "reporter": {"user_id": "demo_rohit", "name": "Rohit Kapoor", "anonymous": False, "picture": None},
        "owner_user_id": "demo_rohit",
        "upvotes": 1556,
        "posted_at": datetime(2026, 2, 7, 8, 0, tzinfo=timezone.utc),
    },
    {
        "issue_id": "PO-DEMO07",
        "title": "Industrial pollution choking lake ecosystem",
        "description": "Factory outlet discharging coloured effluent into Bellandur lake at night. Photos attached. Fish kills reported.",
        "category": "pollution",
        "urgency": "critical",
        "status": "assigned",
        "anonymous": False,
        "photos": [imgWater],
        "location": {"address": "Bellandur Lake, East Bank", "city": "Bengaluru", "district": "Bengaluru Urban", "state": "Karnataka", "pincode": "560103", "lat": 12.9331, "lng": 77.6761},
        "reporter": {"user_id": "demo_env", "name": "Environment Collective", "anonymous": False, "picture": None},
        "owner_user_id": "demo_env",
        "upvotes": 3402,
        "posted_at": datetime(2026, 2, 1, 22, 15, tzinfo=timezone.utc),
    },
    {
        "issue_id": "PO-DEMO08",
        "title": "Ration card office demanding bribes for verification",
        "description": "Multiple citizens report that the verification officer demands ₹500 'expedite fee' to process applications. Receipts never given.",
        "category": "corruption",
        "urgency": "high",
        "status": "under_review",
        "anonymous": True,
        "photos": [imgLight],
        "location": {"address": "Taluk Office, Ernakulam", "city": "Kochi", "district": "Ernakulam", "state": "Kerala", "pincode": "682011", "lat": 9.9816, "lng": 76.2999},
        "reporter": {"user_id": "demo_anon2", "name": "Anonymous", "anonymous": True, "picture": None},
        "owner_user_id": "demo_anon2",
        "upvotes": 1893,
        "posted_at": datetime(2026, 2, 6, 10, 0, tzinfo=timezone.utc),
    },
    {
        "issue_id": "PO-DEMO09",
        "title": "Government school roof collapsed partially — 200 students at risk",
        "description": "The eastern wing roof of Zilla Parishad School has caved in. Classes moved outdoors. Monsoon due in 3 months.",
        "category": "infrastructure",
        "urgency": "critical",
        "status": "assigned",
        "anonymous": False,
        "photos": [imgPothole2],
        "location": {"address": "ZP School, Wardha", "city": "Wardha", "district": "Wardha", "state": "Maharashtra", "pincode": "442001", "lat": 20.7453, "lng": 78.6022},
        "reporter": {"user_id": "demo_pa", "name": "Parents Association", "anonymous": False, "picture": None},
        "owner_user_id": "demo_pa",
        "upvotes": 2187,
        "posted_at": datetime(2026, 2, 4, 8, 0, tzinfo=timezone.utc),
    },
    {
        "issue_id": "PO-DEMO10",
        "title": "Streetlight out for 3 months — women harassment incidents",
        "description": "Stretch between bus stop and colony gate is pitch dark at night. Two eve-teasing incidents reported this month.",
        "category": "safety",
        "urgency": "critical",
        "status": "in_progress",
        "anonymous": False,
        "photos": [imgLight],
        "location": {"address": "DLF Phase 3", "city": "Gurugram", "district": "Gurugram", "state": "Haryana", "pincode": "122002", "lat": 28.4929, "lng": 77.0864},
        "reporter": {"user_id": "demo_nw", "name": "Neighbourhood Watch", "anonymous": False, "picture": None},
        "owner_user_id": "demo_nw",
        "upvotes": 2956,
        "posted_at": datetime(2026, 2, 1, 20, 0, tzinfo=timezone.utc),
    },
]
